apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-postgres-app
  template:
    metadata:
      labels:
        app: my-node-postgres-app
    spec:
      containers:
        - name: my-node-postgres-app
          image: 
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: 
            - name: POSTGRES_PORT
              value: 
            - name: POSTGRES_USER
              value: 
            - name: POSTGRES_PASSWORD
              value: 
            - name: POSTGRES_DB
              value: 