apiVersion: v1
kind: Service
metadata:
  name: my-node-postgres-app-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: my-node-postgres-app